# 1단계: 개발환경 셋팅 -> 브라우저 열기

In [ ]:
# 라이브러리 설치
!pip install selenium webdriver-manager

Collecting selenium
  Downloading selenium-4.41.0-py3-none-any.whl.metadata (7.5 kB)
Collecting webdriver-manager
  Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: certifi>=2026.1.4 in c:\users\admin\miniconda3\envs\webcrawl_env\lib\site-packages (from selenium) (2026.1.4)
Collecting trio<1.0,>=0.31.0 (from selenium)
  Downloading trio-0.33.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in c:\users\admin\miniconda3\envs\webcrawl_env\lib\site-packages (from selenium) (4.15.0)
Requirement already satisfied: urllib3<3.0,>=2.6.3 in c:\users\admin\miniconda3\envs\webcrawl_env\lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (2.6.3)
Collecting websocket-client<2.0,>=1.8.0 (from selenium)
  Using cached websocket_client-1.9.0-py3-none-any.whl.metadata (8.3 kB)
Collecting attrs>=23.2.0 (from trio<1.0,>=0.31.0->selenium)
  Using cached attrs-25.4.0-py3-none-any.whl.metadata (10 kB)
Collecting sortedcontainers (from trio<1.0,>=0.31.0->selenium)
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: idna in c:\users\admin\miniconda3\envs\webcrawl_env\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (3.11)
Collecting outcome (from trio<1.0,>=0.31.0->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Collecting sniffio>=1.3.0 (from trio<1.0,>=0.31.0->selenium)
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting cffi>=1.14 (from trio<1.0,>=0.31.0->selenium)
  Using cached cffi-2.0.0-cp310-cp310-win_amd64.whl.metadata (2.6 kB)
Requirement already satisfied: exceptiongroup in c:\users\admin\miniconda3\envs\webcrawl_env\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.1)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium)
  Downloading wsproto-1.3.2-py3-none-any.whl.metadata (5.2 kB)
Collecting pysocks!=1.5.7,<2.0,>=1.5.6 (from urllib3[socks]<3.0,>=2.6.3->selenium)
  Downloading PySocks-1.7.1-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: requests in c:\users\admin\miniconda3\envs\webcrawl_env\lib\site-packages (from webdriver-manager) (2.32.5)
Collecting python-dotenv (from webdriver-manager)
  Downloading python_dotenv-1.2.2-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: packaging in c:\users\admin\miniconda3\envs\webcrawl_env\lib\site-packages (from webdriver-manager) (26.0)
Collecting pycparser (from cffi>=1.14->trio<1.0,>=0.31.0->selenium)
  Downloading pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Collecting h11<1,>=0.16.0 (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\admin\miniconda3\envs\webcrawl_env\lib\site-packages (from requests->webdriver-manager) (3.4.4)
Downloading selenium-4.41.0-py3-none-any.whl (9.5 MB)
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.5 MB 4.8 MB/s eta 0:00:02
   ------- -------------------------------- 1.8/9.5 MB 4.8 MB/s eta 0:00:02
   ------------- -------------------------- 3.1/9.5 MB 5.1 MB/s eta 0:00:02
   ----------------- ---------------------- 4.2/9.5 MB 5.1 MB/s eta 0:00:02
   -------------------- ------------------- 5.0/9.5 MB 5.1 MB/s eta 0:00:01
   --------------------------- ------------ 6.6/9.5 MB 5.4 MB/s eta 0:00:01
   ---------------------------------- ----- 8.1/9.5 MB 5.7 MB/s eta 0:00:01
   ---------------------------------------- 9.5/9.5 MB 5.8 MB/s  0:00:01
Downloading trio-0.33.0-py3-none-any.whl (510 kB)
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading PySocks-1.7.1-py3-none-any.whl (16 kB)
Using cached websocket_client-1.9.0-py3-none-any.whl (82 kB)
Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl (27 kB)
Using cached attrs-25.4.0-py3-none-any.whl (67 kB)
Using cached cffi-2.0.0-cp310-cp310-win_amd64.whl (182 kB)
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
Downloading wsproto-1.3.2-py3-none-any.whl (24 kB)
Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Downloading pycparser-3.0-py3-none-any.whl (48 kB)
Downloading python_dotenv-1.2.2-py3-none-any.whl (22 kB)
Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Installing collected packages: sortedcontainers, websocket-client, sniffio, python-dotenv, pysocks, pycparser, h11, attrs, wsproto, webdriver-manager, outcome, cffi, trio, trio-websocket, selenium

   -- -------------------------------------  1/15 [websocket-client]
   -- -------------------------------------  1/15 [websocket-client]
   -- -------------------------------------  1/15 [websocket-client]
   -------- -------------------------------  3/15 [python-dotenv]
   ------------- --------------------------  5/15 [pycparser]
   ------------- --------------------------  5/15 [pycparser]
   ------------------ ---------------------  7/15 [attrs]
   ------------------ ---------------------  7/15 [attrs]
   --------------------- ------------------  8/15 [wsproto]
   ------------------------ ---------------  9/15 [webdriver-manager]
   ------------------------ ---------------  9/15 [webdriver-manager]
   ----------------------------- ---------- 11/15 [cffi]
   ----------------------------- ---------- 11/15 [cffi]
   -------------------------------- ------- 12/15 [trio]
   -------------------------------- ------- 12/15 [trio]
   -------------------------------- ------- 12/15 [trio]
   -------------------------------- ------- 12/15 [trio]
   -------------------------------- ------- 12/15 [trio]
   -------------------------------- ------- 12/15 [trio]
   -------------------------------- ------- 12/15 [trio]
   -------------------------------- ------- 12/15 [trio]
   -------------------------------- ------- 12/15 [trio]
   -------------------------------- ------- 12/15 [trio]
   -------------------------------- ------- 12/15 [trio]
   -------------------------------- ------- 12/15 [trio]
   -------------------------------- ------- 12/15 [trio]
   -------------------------------- ------- 12/15 [trio]
   -------------------------------- ------- 12/15 [trio]
   -------------------------------- ------- 12/15 [trio]
   -------------------------------- ------- 12/15 [trio]
   -------------------------------- ------- 12/15 [trio]
   -------------------------------- ------- 12/15 [trio]
   -------------------------------- ------- 12/15 [trio]
   -------------------------------- ------- 12/15 [trio]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ------------------------------------- -- 14/15 [selenium]
   ---------------------------------------- 15/15 [selenium]

Successfully installed attrs-25.4.0 cffi-2.0.0 h11-0.16.0 outcome-1.3.0.post0 pycparser-3.0 pysocks-1.7.1 python-dotenv-1.2.2 selenium-4.41.0 sniffio-1.3.1 sortedcontainers-2.4.0 trio-0.33.0 trio-websocket-0.12.2 webdriver-manager-4.0.2 websocket-client-1.9.0 wsproto-1.3.2

In [ ]:
# 라이브러리 불러오기
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

import time

In [4]:
# 크롬 브라우저 실행

# 크롬 옵션 설정
options = Options()
options.add_argument("--start-maximized")   # 창 최대화
options.add_argument("--disable-blink-features=AutomationControlled")

# 드라이버 실행
driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
)

# 엔카 홈페이지 열기
driver.get("https://www.encar.com/index.do")

# 페이지가 열릴 때까지 잠깐 대기
time.sleep(3)

print("엔카 홈페이지 접속 완료")
print("현재 URL:", driver.current_url)
print("페이지 제목:", driver.title)

엔카 홈페이지 접속 완료
현재 URL: https://www.encar.com/index.do
페이지 제목: 내차팔기·내차사기 | 엔카

In [5]:
# 크롬창 잘 열렸는지 확인
print(driver.title)

내차팔기·내차사기 | 엔카

# 2단계: 자동 이동 실행

In [6]:
# 클릭 보조함수 만들기

wait = WebDriverWait(driver, 15)

def safe_click(candidates, name):
    last_error = None
    
    for by, selector in candidates:
        try:
            elem = wait.until(EC.presence_of_element_located((by, selector)))
            driver.execute_script("arguments[0].scrollIntoView({block:'center'});", elem)
            time.sleep(1)
            
            try:
                wait.until(EC.element_to_be_clickable((by, selector)))
                elem.click()
            except:
                driver.execute_script("arguments[0].click();", elem)
            
            print(f"{name} 클릭 완료")
            time.sleep(2)
            return
        
        except Exception as e:
            last_error = e
    
    raise last_error

In [7]:
# 엔카 메인 이동
driver.get("https://www.encar.com/index.do")
time.sleep(3)

print("현재 URL:", driver.current_url)
print("페이지 제목:", driver.title)

현재 URL: https://www.encar.com/index.do
페이지 제목: 내차팔기·내차사기 | 엔카

In [8]:
# 국산 -> 현대 -> 그렌저 클릭 

# 1) 국산 클릭 후보
domestic_candidates = [
    (By.XPATH, "//a[normalize-space()='국산']"),
    (By.XPATH, "//button[normalize-space()='국산']"),
    (By.XPATH, "//*[normalize-space()='국산']/ancestor::*[self::a or self::button][1]")
]

# 2) 현대 클릭 후보
hyundai_candidates = [
    (By.XPATH, "//a[normalize-space()='현대']"),
    (By.XPATH, "//button[normalize-space()='현대']"),
    (By.XPATH, "//label[normalize-space()='현대']"),
    (By.XPATH, "//*[normalize-space()='현대']/ancestor::*[self::a or self::button or self::label][1]")
]

# 3) 그랜저 클릭 후보
grandeur_candidates = [
    (By.XPATH, "//a[normalize-space()='그랜저']"),
    (By.XPATH, "//button[normalize-space()='그랜저']"),
    (By.XPATH, "//label[normalize-space()='그랜저']"),
    (By.XPATH, "//*[normalize-space()='그랜저']/ancestor::*[self::a or self::button or self::label][1]")
]

# 클릭 실행
safe_click(domestic_candidates, "국산")
safe_click(hyundai_candidates, "현대")
safe_click(grandeur_candidates, "그랜저")

print("2단계 이동 완료")
print("현재 URL:", driver.current_url)
print("페이지 제목:", driver.title)

국산 클릭 완료
현대 클릭 완료
그랜저 클릭 완료
2단계 이동 완료
현재 URL: https://www.encar.com/dc/dc_carsearchlist.do?carType=kor#!%7B%22action%22%3A%22(And.Hidden.N._.(C.CarType.Y._.(C.Manufacturer.%ED%98%84%EB%8C%80._.ModelGroup.%EA%B7%B8%EB%9E%9C%EC%A0%80.)))%22%2C%22toggle%22%3A%7B%7D%2C%22layer%22%3A%22%22%2C%22sort%22%3A%22ModifiedDate%22%2C%22page%22%3A1%2C%22limit%22%3A20%2C%22searchKey%22%3A%22%22%2C%22loginCheck%22%3Afalse%7D
페이지 제목: 엔카믿고 현대 그랜저 중고차

# 3단계: 목록 페이지에서 매물 카드 구조 확인

In [9]:
# 상세페이지 링크 개수 확인

wait = WebDriverWait(driver, 15)

# 상세페이지 링크가 뜰 때까지 대기
wait.until(
    EC.presence_of_element_located(
        (By.XPATH, "//a[contains(@href, '/cars/detail/') or contains(@href, 'carid=')]")
    )
)

detail_links = driver.find_elements(
    By.XPATH,
    "//a[contains(@href, '/cars/detail/') or contains(@href, 'carid=')]"
)

print("상세페이지 링크 수:", len(detail_links))

# 앞 5개 링크 미리 보기
for i, link in enumerate(detail_links[:5], 1):
    print(f"\n[{i}]")
    print("text :", link.text.strip())
    print("href :", link.get_attribute("href"))

상세페이지 링크 수: 78

[1]
text : 찜
현대 그랜저 (GN7) 3.5 LPG 2WD 프리미엄
22/12식(23년형)
· 51,000km
LPG(일반인 구입)
· 경기
렌트 월 100만원/1개월
href : https://www.encar.com/dc/dc_cardetailview.do?pageid=dc_carsearch&listAdvType=pic&carid=40241113&view_type=normal&wtClick_korList=015&advClickPosition=kor_pic_p1_g1

[2]
text : 찜
현대 그랜저 (GN7) 3.5 LPG 2WD 프리미엄
23/11식
· 22,500km
LPG(일반인 구입)
· 경기
렌트 월 100만원/1개월
href : https://www.encar.com/dc/dc_cardetailview.do?pageid=dc_carsearch&listAdvType=pic&carid=40213135&view_type=normal&wtClick_korList=015&advClickPosition=kor_pic_p1_g2

[3]
text : 찜
현대 그랜저 하이브리드 (GN7) 프리미엄
23/12식(24년형)
· 20,000km
가솔린+전기
· 경기
렌트 월 120만원/1개월
href : https://www.encar.com/dc/dc_cardetailview.do?pageid=dc_carsearch&listAdvType=pic&carid=40213183&view_type=normal&wtClick_korList=015&advClickPosition=kor_pic_p1_g3

[4]
text : 찜
현대 더 뉴 그랜저 IG 하이브리드 캘리그래피
20/10식
· 58,023km
가솔린+전기
· 부산
2,790만원
href : https://www.encar.com/dc/dc_cardetailview.do?pageid=dc_carsearch&listAdvType=pic&carid=41634003&view_type=normal&wtClick_korList=015&advClickPosition=kor_pic_p1_g4

[5]
text : 진단
찜
현대 더 뉴 그랜저 IG 2.5 캘리그래피
20/12식(21년형)
· 151,434km
가솔린
· 서울
1,990만원
href : https://www.encar.com/dc/dc_cardetailview.do?pageid=dc_carsearch&listAdvType=pic&carid=39342767&view_type=checked&wtClick_korList=015&advClickPosition=kor_pic_p1_g5

In [10]:
# 첫 번째 매물카드의 상위 구조 보기

first_link = detail_links[0]

# 링크 기준으로 상위 요소를 몇 단계 올라가며 출력해보기
parent_1 = first_link.find_element(By.XPATH, "./..")
parent_2 = first_link.find_element(By.XPATH, "./../..")
parent_3 = first_link.find_element(By.XPATH, "./../../..")

print("=== parent_1 ===")
print(parent_1.get_attribute("outerHTML")[:1000])

print("\n=== parent_2 ===")
print(parent_2.get_attribute("outerHTML")[:1500])

print("\n=== parent_3 ===")
print(parent_3.get_attribute("outerHTML")[:2000])

=== parent_1 ===
<li data-index="0" data-impression="40241113|4010|8680|t1|pic1|8|1" data-impression-index="0"> <a href="/dc/dc_cardetailview.do?pageid=dc_carsearch&amp;listAdvType=pic&amp;carid=40241113&amp;view_type=normal&amp;wtClick_korList=015&amp;advClickPosition=kor_pic_p1_g1" class="newLink _link" target="_blank" data-enlog-dt-eventname="차량상세" data-enlog-dt-hit="list_pic" data-enlog-dt-param="{'filter': '(And.Hidden.N._.(C.CarType.Y._.(C.Manufacturer.현대._.ModelGroup.그랜저.)))', 'carid': '40241113', 'sorttype': 'ModifiedDate'}"><span class="img"><span class="blt UIimageScrollLoadEnd"><img class="thumb UIimageScrollLoad" src="https://ci.encar.com/carpicture/carpicture04/pic4024/40241113_001.jpg?impolicy=heightRate&amp;rh=192&amp;cw=320&amp;ch=192&amp;cg=Center&amp;wtmk=https://ci.encar.com/wt_mark/w_mark_04.png&amp;wtmkg=SouthEast&amp;wtmkw=70&amp;wtmkh=30&amp;t=20250805171722" alt=""></span> <span class="ic_zzim"> <button type="button" class="btn_zzim btn_zzim_s " data-enlog-dt-eventname="찜하기" dat

=== parent_2 ===
<ul class="car_list" id="sr_photo" data-role="list_container" data-bind="html: renderPhotoSearchResults()">   <li data-index="0" data-impression="40241113|4010|8680|t1|pic1|8|1" data-impression-index="0"> <a href="/dc/dc_cardetailview.do?pageid=dc_carsearch&amp;listAdvType=pic&amp;carid=40241113&amp;view_type=normal&amp;wtClick_korList=015&amp;advClickPosition=kor_pic_p1_g1" class="newLink _link" target="_blank" data-enlog-dt-eventname="차량상세" data-enlog-dt-hit="list_pic" data-enlog-dt-param="{'filter': '(And.Hidden.N._.(C.CarType.Y._.(C.Manufacturer.현대._.ModelGroup.그랜저.)))', 'carid': '40241113', 'sorttype': 'ModifiedDate'}"><span class="img"><span class="blt UIimageScrollLoadEnd"><img class="thumb UIimageScrollLoad" src="https://ci.encar.com/carpicture/carpicture04/pic4024/40241113_001.jpg?impolicy=heightRate&amp;rh=192&amp;cw=320&amp;ch=192&amp;cg=Center&amp;wtmk=https://ci.encar.com/wt_mark/w_mark_04.png&amp;wtmkg=SouthEast&amp;wtmkw=70&amp;wtmkh=30&amp;t=20250805171722" alt=""></span> <span class="ic_zzim"> <button type="button" class="btn_zzim btn_zzim_s " data-enlog-dt-eventname="찜하기" data-enlog-dt-param="{'filter': '(And.Hidden.N._.(C.CarType.Y._.(C.Manufacturer.현대._.ModelGroup.그랜저.)))', 'carid': '40241113', 'sorttype': 'ModifiedDate'}">찜</button> </span></span> <span class="inf"><span class="cls"><strong>현대</strong> <em>그랜저 (GN7)</em></span><span class="dtl"><strong> 3.5 LPG 2WD</strong> <em>프리미엄</em></span></span> <span class="detail"><span class="yer">22/12식<em>(23년형

=== parent_3 ===
<div class="part list">
                    <ul class="car_list" id="sr_photo" data-role="list_container" data-bind="html: renderPhotoSearchResults()">   <li data-index="0" data-impression="40241113|4010|8680|t1|pic1|8|1" data-impression-index="0"> <a href="/dc/dc_cardetailview.do?pageid=dc_carsearch&amp;listAdvType=pic&amp;carid=40241113&amp;view_type=normal&amp;wtClick_korList=015&amp;advClickPosition=kor_pic_p1_g1" class="newLink _link" target="_blank" data-enlog-dt-eventname="차량상세" data-enlog-dt-hit="list_pic" data-enlog-dt-param="{'filter': '(And.Hidden.N._.(C.CarType.Y._.(C.Manufacturer.현대._.ModelGroup.그랜저.)))', 'carid': '40241113', 'sorttype': 'ModifiedDate'}"><span class="img"><span class="blt UIimageScrollLoadEnd"><img class="thumb UIimageScrollLoad" src="https://ci.encar.com/carpicture/carpicture04/pic4024/40241113_001.jpg?impolicy=heightRate&amp;rh=192&amp;cw=320&amp;ch=192&amp;cg=Center&amp;wtmk=https://ci.encar.com/wt_mark/w_mark_04.png&amp;wtmkg=SouthEast&amp;wtmkw=70&amp;wtmkh=30&amp;t=20250805171722" alt=""></span> <span class="ic_zzim"> <button type="button" class="btn_zzim btn_zzim_s " data-enlog-dt-eventname="찜하기" data-enlog-dt-param="{'filter': '(And.Hidden.N._.(C.CarType.Y._.(C.Manufacturer.현대._.ModelGroup.그랜저.)))', 'carid': '40241113', 'sorttype': 'ModifiedDate'}">찜</button> </span></span> <span class="inf"><span class="cls"><strong>현대</strong> <em>그랜저 (GN7)</em></span><span class="dtl"><strong> 3.5 LPG 2WD</strong> <em>프리미엄</em></span></span> <span class="detail"><span class="yer">22/12식<em>(23년형)</em></span><span class="km">· 51,000km</span><span class="ipt">LPG(일반인 구입)</span><span class="lo">· 경기</span></span> <span class="val">   <em class="txt_leaserent">렌트</em>  <em class="txt_month">월</em>   <span class="prc"><strong>100</strong>만원<span class="remain">/1개월</span></span>    </span> <span class="service_label_list">    </span> </a> </li>   <li data-index="1" data-impression="40213135|4010|8680|t2|pic2|8|1" data-impression-index="1"> <a hre

In [11]:
# 첫 번째 카드의 텍스트만 보기 

print("=== 첫 번째 링크 text ===")
print(first_link.text)

print("\n=== parent_1 text ===")
print(parent_1.text)

print("\n=== parent_2 text ===")
print(parent_2.text)

print("\n=== parent_3 text ===")
print(parent_3.text)

=== 첫 번째 링크 text ===
찜
현대 그랜저 (GN7) 3.5 LPG 2WD 프리미엄
22/12식(23년형)
· 51,000km
LPG(일반인 구입)
· 경기
렌트 월 100만원/1개월

=== parent_1 text ===
찜
현대 그랜저 (GN7) 3.5 LPG 2WD 프리미엄
22/12식(23년형)
· 51,000km
LPG(일반인 구입)
· 경기
렌트 월 100만원/1개월

=== parent_2 text ===
찜
현대 그랜저 (GN7) 3.5 LPG 2WD 프리미엄
22/12식(23년형)
· 51,000km
LPG(일반인 구입)
· 경기
렌트 월 100만원/1개월
찜
현대 그랜저 (GN7) 3.5 LPG 2WD 프리미엄
23/11식
· 22,500km
LPG(일반인 구입)
· 경기
렌트 월 100만원/1개월
찜
현대 그랜저 하이브리드 (GN7) 프리미엄
23/12식(24년형)
· 20,000km
가솔린+전기
· 경기
렌트 월 120만원/1개월
찜
현대 더 뉴 그랜저 IG 하이브리드 캘리그래피
20/10식
· 58,023km
가솔린+전기
· 부산
2,790만원
진단
찜
현대 더 뉴 그랜저 IG 2.5 캘리그래피
20/12식(21년형)
· 151,434km
가솔린
· 서울
1,990만원
진단
찜
현대 그랜저 HG 하이브리드 프리미엄
14/05식(15년형)
· 183,217km
가솔린+전기
· 경기
620만원
진단+
찜
현대 그랜저 하이브리드 (GN7) 익스클루시브
23/11식
· 17,805km
가솔린+전기
· 서울
3,730만원
찜
현대 그랜저 하이브리드 (GN7) 익스클루시브
23/04식
· 66,588km
가솔린+전기
· 광주
3,400만원

=== parent_3 text ===
찜
현대 그랜저 (GN7) 3.5 LPG 2WD 프리미엄
22/12식(23년형)
· 51,000km
LPG(일반인 구입)
· 경기
렌트 월 100만원/1개월
찜
현대 그랜저 (GN7) 3.5 LPG 2WD 프리미엄
23/11식
· 22,500km
LPG(일반인 구입)
· 경기
렌트 월 100만원/1개월
찜
현대 그랜저 하이브리드 (GN7) 프리미엄
23/12식(24년형)
· 20,000km
가솔린+전기
· 경기
렌트 월 120만원/1개월
찜
현대 더 뉴 그랜저 IG 하이브리드 캘리그래피
20/10식
· 58,023km
가솔린+전기
· 부산
2,790만원
진단
찜
현대 더 뉴 그랜저 IG 2.5 캘리그래피
20/12식(21년형)
· 151,434km
가솔린
· 서울
1,990만원
진단
찜
현대 그랜저 HG 하이브리드 프리미엄
14/05식(15년형)
· 183,217km
가솔린+전기
· 경기
620만원
진단+
찜
현대 그랜저 하이브리드 (GN7) 익스클루시브
23/11식
· 17,805km
가솔린+전기
· 서울
3,730만원
찜
현대 그랜저 하이브리드 (GN7) 익스클루시브
23/04식
· 66,588km
가솔린+전기
· 광주
3,400만원

In [12]:
# 상세링크가 1개만 들어 있는 상위요소 찾기

current = detail_links[0]

for i in range(1, 6):
    current = current.find_element(By.XPATH, "./..")
    links_in_box = current.find_elements(By.XPATH, ".//a[contains(@href, '/cars/detail/') or contains(@href, 'carid=')]")
    
    print(f"\n=== 상위 {i}단계 ===")
    print("상세링크 개수:", len(links_in_box))
    print(current.text[:500])

=== 상위 1단계 ===
상세링크 개수: 1
찜
현대 그랜저 (GN7) 3.5 LPG 2WD 프리미엄
22/12식(23년형)
· 51,000km
LPG(일반인 구입)
· 경기
렌트 월 100만원/1개월

=== 상위 2단계 ===
상세링크 개수: 8
찜
현대 그랜저 (GN7) 3.5 LPG 2WD 프리미엄
22/12식(23년형)
· 51,000km
LPG(일반인 구입)
· 경기
렌트 월 100만원/1개월
찜
현대 그랜저 (GN7) 3.5 LPG 2WD 프리미엄
23/11식
· 22,500km
LPG(일반인 구입)
· 경기
렌트 월 100만원/1개월
찜
현대 그랜저 하이브리드 (GN7) 프리미엄
23/12식(24년형)
· 20,000km
가솔린+전기
· 경기
렌트 월 120만원/1개월
찜
현대 더 뉴 그랜저 IG 하이브리드 캘리그래피
20/10식
· 58,023km
가솔린+전기
· 부산
2,790만원
진단
찜
현대 더 뉴 그랜저 IG 2.5 캘리그래피
20/12식(21년형)
· 151,434km
가솔린
· 서울
1,990만원
진단
찜
현대 그랜저 HG 하이브리드 프리미엄
14/05식(15년형)
· 183,217km
가솔린+전기
· 경기
620만원
진단+
찜
현대 그랜저 하이브리드 (GN7) 익스클루시브
23/11식
· 17,805

=== 상위 3단계 ===
상세링크 개수: 8
찜
현대 그랜저 (GN7) 3.5 LPG 2WD 프리미엄
22/12식(23년형)
· 51,000km
LPG(일반인 구입)
· 경기
렌트 월 100만원/1개월
찜
현대 그랜저 (GN7) 3.5 LPG 2WD 프리미엄
23/11식
· 22,500km
LPG(일반인 구입)
· 경기
렌트 월 100만원/1개월
찜
현대 그랜저 하이브리드 (GN7) 프리미엄
23/12식(24년형)
· 20,000km
가솔린+전기
· 경기
렌트 월 120만원/1개월
찜
현대 더 뉴 그랜저 IG 하이브리드 캘리그래피
20/10식
· 58,023km
가솔린+전기
· 부산
2,790만원
진단
찜
현대 더 뉴 그랜저 IG 2.5 캘리그래피
20/12식(21년형)
· 151,434km
가솔린
· 서울
1,990만원
진단
찜
현대 그랜저 HG 하이브리드 프리미엄
14/05식(15년형)
· 183,217km
가솔린+전기
· 경기
620만원
진단+
찜
현대 그랜저 하이브리드 (GN7) 익스클루시브
23/11식
· 17,805

=== 상위 4단계 ===
상세링크 개수: 8
사진우대
사진우대 안내
찜
현대 그랜저 (GN7) 3.5 LPG 2WD 프리미엄
22/12식(23년형)
· 51,000km
LPG(일반인 구입)
· 경기
렌트 월 100만원/1개월
찜
현대 그랜저 (GN7) 3.5 LPG 2WD 프리미엄
23/11식
· 22,500km
LPG(일반인 구입)
· 경기
렌트 월 100만원/1개월
찜
현대 그랜저 하이브리드 (GN7) 프리미엄
23/12식(24년형)
· 20,000km
가솔린+전기
· 경기
렌트 월 120만원/1개월
찜
현대 더 뉴 그랜저 IG 하이브리드 캘리그래피
20/10식
· 58,023km
가솔린+전기
· 부산
2,790만원
진단
찜
현대 더 뉴 그랜저 IG 2.5 캘리그래피
20/12식(21년형)
· 151,434km
가솔린
· 서울
1,990만원
진단
찜
현대 그랜저 HG 하이브리드 프리미엄
14/05식(15년형)
· 183,217km
가솔린+전기
· 경기
620만원
진단+
찜
현대 그랜저 하이브리드 (GN7) 익스클루시브
23

=== 상위 5단계 ===
상세링크 개수: 78
현대 선택초기화

사진우대
사진우대 안내
찜
현대 그랜저 (GN7) 3.5 LPG 2WD 프리미엄
22/12식(23년형)
· 51,000km
LPG(일반인 구입)
· 경기
렌트 월 100만원/1개월
찜
현대 그랜저 (GN7) 3.5 LPG 2WD 프리미엄
23/11식
· 22,500km
LPG(일반인 구입)
· 경기
렌트 월 100만원/1개월
찜
현대 그랜저 하이브리드 (GN7) 프리미엄
23/12식(24년형)
· 20,000km
가솔린+전기
· 경기
렌트 월 120만원/1개월
찜
현대 더 뉴 그랜저 IG 하이브리드 캘리그래피
20/10식
· 58,023km
가솔린+전기
· 부산
2,790만원
진단
찜
현대 더 뉴 그랜저 IG 2.5 캘리그래피
20/12식(21년형)
· 151,434km
가솔린
· 서울
1,990만원
진단
찜
현대 그랜저 HG 하이브리드 프리미엄
14/05식(15년형)
· 183,217km
가솔린+전기
· 경기
620만원
진단+
찜
현대 그랜저 하이브리드 (GN7)

# 4단계: 카드 텍스트 전체를 먼저 수집

In [13]:
# 수집된 카드 수 및 첫 번째 카드 예시

cards = []

for link in detail_links:
    try:
        card = link.find_element(By.XPATH, "./..")   # 상위 1단계 = 카드 1개
        title = link.get_attribute("title")
        href = link.get_attribute("href")
        text = card.text.strip()
        
        cards.append({
            "title": title,
            "detail_url": href,
            "card_text": text
        })
    except Exception as e:
        print("에러 발생:", e)

print("수집된 카드 수:", len(cards))
print("\n첫 번째 카드 예시:")
print(cards[0])

수집된 카드 수: 78

첫 번째 카드 예시:
{'title': '', 'detail_url': 'https://www.encar.com/dc/dc_cardetailview.do?pageid=dc_carsearch&listAdvType=pic&carid=40241113&view_type=normal&wtClick_korList=015&advClickPosition=kor_pic_p1_g1', 'card_text': '찜\n현대 그랜저 (GN7) 3.5 LPG 2WD 프리미엄\n22/12식(23년형)\n· 51,000km\nLPG(일반인 구입)\n· 경기\n렌트 월 100만원/1개월'}

In [14]:
# card_text 컬럼으로 분리하기

import re
import pandas as pd

def clean_line(line):
    line = line.strip()
    line = re.sub(r'^[·•]\s*', '', line)   # 앞의 점 제거
    return line

def parse_card_text(text):
    lines = [clean_line(x) for x in text.split("\n")]
    lines = [x for x in lines if x and x != "찜"]   # 빈 줄, '찜' 제거
    
    result = {
        "car_name": "",
        "year_info": "",
        "mileage": "",
        "fuel": "",
        "region": "",
        "price_info": ""
    }
    
    if len(lines) >= 1:
        result["car_name"] = lines[0]
    if len(lines) >= 2:
        result["year_info"] = lines[1]
    if len(lines) >= 3:
        result["mileage"] = lines[2]
    if len(lines) >= 4:
        result["fuel"] = lines[3]
    if len(lines) >= 5:
        result["region"] = lines[4]
    if len(lines) >= 6:
        result["price_info"] = " ".join(lines[5:])   # 뒤에 여러 줄이 있어도 합치기
    
    return result


parsed_cards = []

for card in cards:
    parsed = parse_card_text(card["card_text"])
    parsed["detail_url"] = card["detail_url"]
    parsed_cards.append(parsed)

list_df = pd.DataFrame(parsed_cards)

print("데이터 개수:", len(list_df))
list_df.head(10)

데이터 개수: 78

,car_name,year_info,mileage,fuel,region,price_info,detail_url
0,현대 그랜저 (GN7) 3.5 LPG 2WD 프리미엄,22/12식(23년형),"51,000km",LPG(일반인 구입),경기,렌트 월 100만원/1개월,https://www.encar.com/dc/dc_cardetailview.do?p...
1,현대 그랜저 (GN7) 3.5 LPG 2WD 프리미엄,23/11식,"22,500km",LPG(일반인 구입),경기,렌트 월 100만원/1개월,https://www.encar.com/dc/dc_cardetailview.do?p...
2,현대 그랜저 하이브리드 (GN7) 프리미엄,23/12식(24년형),"20,000km",가솔린+전기,경기,렌트 월 120만원/1개월,https://www.encar.com/dc/dc_cardetailview.do?p...
3,현대 더 뉴 그랜저 IG 하이브리드 캘리그래피,20/10식,"58,023km",가솔린+전기,부산,"2,790만원",https://www.encar.com/dc/dc_cardetailview.do?p...
4,진단,현대 더 뉴 그랜저 IG 2.5 캘리그래피,20/12식(21년형),"151,434km",가솔린,"서울 1,990만원",https://www.encar.com/dc/dc_cardetailview.do?p...
5,진단,현대 그랜저 HG 하이브리드 프리미엄,14/05식(15년형),"183,217km",가솔린+전기,경기 620만원,https://www.encar.com/dc/dc_cardetailview.do?p...
6,진단+,현대 그랜저 하이브리드 (GN7) 익스클루시브,23/11식,"17,805km",가솔린+전기,"서울 3,730만원",https://www.encar.com/dc/dc_cardetailview.do?p...
7,현대 그랜저 하이브리드 (GN7) 익스클루시브,23/04식,"66,588km",가솔린+전기,광주,"3,400만원",https://www.encar.com/dc/dc_cardetailview.do?p...
8,,,,,,,https://www.encar.com/dc/dc_cardetailview.do?p...
9,,,,,,,https://www.encar.com/dc/dc_cardetailview.do?p...

In [15]:
list_df.head()

,car_name,year_info,mileage,fuel,region,price_info,detail_url
0,현대 그랜저 (GN7) 3.5 LPG 2WD 프리미엄,22/12식(23년형),"51,000km",LPG(일반인 구입),경기,렌트 월 100만원/1개월,https://www.encar.com/dc/dc_cardetailview.do?p...
1,현대 그랜저 (GN7) 3.5 LPG 2WD 프리미엄,23/11식,"22,500km",LPG(일반인 구입),경기,렌트 월 100만원/1개월,https://www.encar.com/dc/dc_cardetailview.do?p...
2,현대 그랜저 하이브리드 (GN7) 프리미엄,23/12식(24년형),"20,000km",가솔린+전기,경기,렌트 월 120만원/1개월,https://www.encar.com/dc/dc_cardetailview.do?p...
3,현대 더 뉴 그랜저 IG 하이브리드 캘리그래피,20/10식,"58,023km",가솔린+전기,부산,"2,790만원",https://www.encar.com/dc/dc_cardetailview.do?p...
4,진단,현대 더 뉴 그랜저 IG 2.5 캘리그래피,20/12식(21년형),"151,434km",가솔린,"서울 1,990만원",https://www.encar.com/dc/dc_cardetailview.do?p...

# 5단계: 상세페이지 1건 들어가서 상세 정보 구조 확인

In [16]:
# 첫 번째 상세 페이지 열기

detail_url = list_df.loc[0, "detail_url"]
print(detail_url)

driver.get(detail_url)
time.sleep(3)

print("현재 URL:", driver.current_url)
print("페이지 제목:", driver.title)

https://www.encar.com/dc/dc_cardetailview.do?pageid=dc_carsearch&listAdvType=pic&carid=40241113&view_type=normal&wtClick_korList=015&advClickPosition=kor_pic_p1_g1
현재 URL: https://fem.encar.com/cars/detail/40241113?pageid=dc_carsearch&listAdvType=pic&carid=40241113&view_type=normal&wtClick_korList=015&advClickPosition=kor_pic_p1_g1
페이지 제목: 그랜저 (GN7) 3.5 LPG 2WD 프리미엄 경기 중고차 : 내차팔기·내차사기

In [ ]:
# 상세페이지 전체 텍스트 추출
body_text = driver.find_element(By.TAG_NAME, "body").text

print(body_text[:3000])

엔카
기본정보
옵션정보
렌트정보
보증현황
판매자 정보
딜러 셀프등록
로그인/회원가입
채팅
전체메뉴
열기
등록번호 40241113조회수 150찜 0
신고하기
프린트
공유하기
찜하기
#양호#HOT#COOL
엔카 실촬영
이전이미지
다음이미지
1 / 11
사진 모두보기
엔카 제휴사에서 선별한 차량입니다.
리스 · 렌트제휴 차량 검색
제휴사 소개
그랜저 (GN7)3.5 LPG 2WD프리미엄
연식
22/12식 (23년형)
연형정보
주행거리
51,000km
연료
LPG(일반인 구입)
차량번호
101하9880
자세히
옵션 정보더보기
주요옵션
옵션 설명 보기
선루프
있음
헤드램프
(LED)
있음
주차감지센서
있음
후방카메라
있음
자동에어컨
있음
스마트키
있음
내비게이션
있음
열선시트
있음
통풍시트
없음
가죽시트
있음
40개 옵션 모두보기
이 차만의 옵션더보기
파노라마 선루프 120만원
렌트 정보
차량 계약 시 비용
보증금 방식
50만원
운행기간 동안 비용
월렌트료 100만원 X 1개월
월렌트료 97만원 X 3개월
100만원
렌트 만기 후 비용
렌트 만기 후 비용
반납 (보증금 환급)
50만원
총비용
100만원
체크포인트
렌트방식 장기렌트
취등록세(7%) 면제
월렌트료 포함내역 자동차 세금보험료정비서비스
상환 스케줄표 없음
만기 후 처리 반납
렌트 정보 자세히 보기
보증 현황
제조사 보증제조사보증도움말
일반/차체
엔진/미션
엔카금융
1분만에 한도/금리 비교
다양한 금융사의 금리를 비교해보세요
방문없이 조회가 가능해요
신용점수에 영향이 없어요
금리 비교하기
판매자 정보
판매자정보사진
토마토렌트카|토마토렌트카반복
판매자 정보
판매중18판매완료0
경기 성남시 수정구
엔카 제휴사에서 선별한 차량입니다.
토마토렌트카는 중고차 신차 구분없이 1개월부터 60개월까지 신용심사 없이 누구나 이용 가능한 렌트 서비스를 제공합니다.
구매 가이드
허위매물 대처
압류 및 저당 처리
성능 상태 점검기록부
차량 금액 외 별도 수수료
차량 이전등록
차량 체크사항
알림등록
비슷한 조건의 동일한 모델이 신규매물로 등록되면 알려드릴까요?
알림등록
월100만원
월렌트료(1개월)
월렌트료도움말
보험료 계산
대출상품 조회
리스상품 조회
보증금
보증금자세히 보기
50 만원
차량가격
차량 가격 자세히 보기
4,010 만원
보험이력
비공개
신차가격표
판매자 문의하기
중고차시세
팔린매물
동급매물
엔카 중고차론
금융사 비교하고 제휴 추가할인
금리 4.9% 부터~
닫기
허위매물 단속 및 매매관련 분쟁 처리 등을 위해 050안심번호로문의하면 전화번호와 통화내용이 엔카에 자동 저장됩니다.050도움말
엔카는 등록 시스템만을 제공하며, 판매자가 직접 등록한 차량의 모든 책임은 판매자에게 있습니다. 신고하기
회사소개인재채용클린엔카지점안내엔카직영성능점검장안내매매지원이용약관고객센터디스플레이광고개인정보처리방침금융소비자보호원격지원서비스
네이버 블로그
인스타그램
유튜브
페이스북
패밀리사이트
O2O를 잇는 신뢰와 기술로 차량을 사고 파는 모습의 진화를 만듭니다
고객센터 : 1599-5455FAX : 02-754-8768대표메일 : trust@encar.com주소 : 서울특별시 중구 통일로2길 16, 18~19층(순화동)
사업자 등록번호 : 104-86-54476통신판매업신고 : 제2014-서울중구-0393호대표자 : 김상범Copyright © 엔카닷컴(주)
내 차를 최고가에 팔고, 믿고 사는 가장 좋은 방법. 엔카닷컴(주)
엔카닷컴(주)는 통신판매중개자로서 통신판매의 당사자가 아니며, 상품·거래정보, 거래에 대하여 책임을 지지 않습니다.

In [18]:
# 상세페이지가 맞는지 확인

print("현재 URL:", driver.current_url)
print("페이지 제목:", driver.title)

현재 URL: https://fem.encar.com/cars/detail/40241113?pageid=dc_carsearch&listAdvType=pic&carid=40241113&view_type=normal&wtClick_korList=015&advClickPosition=kor_pic_p1_g1
페이지 제목: 그랜저 (GN7) 3.5 LPG 2WD 프리미엄 경기 중고차 : 내차팔기·내차사기

In [19]:
# 상세 본문 후보 찾기

candidates = []

elements = driver.find_elements(By.XPATH, "//*[self::div or self::section or self::article]")

for elem in elements:
    try:
        if not elem.is_displayed():
            continue
        
        text = elem.text.strip()
        
        if len(text) < 100:
            continue
        
        if "기본정보" in text and ("옵션정보" in text or "판매자 정보" in text):
            candidates.append({
                "tag": elem.tag_name,
                "id": elem.get_attribute("id"),
                "class": elem.get_attribute("class"),
                "text": text
            })
    except:
        pass

print("후보 개수:", len(candidates))

for i, c in enumerate(candidates[:5], 1):
    print(f"\n===== 후보 {i} =====")
    print("tag   :", c["tag"])
    print("id    :", c["id"])
    print("class :", c["class"])
    print(c["text"][:1500])

후보 개수: 4

===== 후보 1 =====
tag   : div
id    : wrap
class :
엔카
기본정보
옵션정보
렌트정보
보증현황
판매자 정보
딜러 셀프등록
로그인/회원가입
채팅
전체메뉴
열기
등록번호 40241113조회수 150찜 0
신고하기
프린트
공유하기
찜하기
#양호#HOT#COOL
엔카 실촬영
이전이미지
다음이미지
1 / 11
사진 모두보기
엔카 제휴사에서 선별한 차량입니다.
리스 · 렌트제휴 차량 검색
제휴사 소개
그랜저 (GN7)3.5 LPG 2WD프리미엄
연식
22/12식 (23년형)
연형정보
주행거리
51,000km
연료
LPG(일반인 구입)
차량번호
101하9880
자세히
옵션 정보더보기
주요옵션
옵션 설명 보기
선루프
있음
헤드램프
(LED)
있음
주차감지센서
있음
후방카메라
있음
자동에어컨
있음
스마트키
있음
내비게이션
있음
열선시트
있음
통풍시트
없음
가죽시트
있음
40개 옵션 모두보기
이 차만의 옵션더보기
파노라마 선루프 120만원
렌트 정보
차량 계약 시 비용
보증금 방식
50만원
운행기간 동안 비용
월렌트료 100만원 X 1개월
월렌트료 97만원 X 3개월
100만원
렌트 만기 후 비용
렌트 만기 후 비용
반납 (보증금 환급)
50만원
총비용
100만원
체크포인트
렌트방식 장기렌트
취등록세(7%) 면제
월렌트료 포함내역 자동차 세금보험료정비서비스
상환 스케줄표 없음
만기 후 처리 반납
렌트 정보 자세히 보기
보증 현황
제조사 보증제조사보증도움말
일반/차체
엔진/미션
엔카금융
1분만에 한도/금리 비교
다양한 금융사의 금리를 비교해보세요
방문없이 조회가 가능해요
신용점수에 영향이 없어요
금리 비교하기
판매자 정보
판매자정보사진
토마토렌트카|토마토렌트카반복
판매자 정보
판매중18판매완료0
경기 성남시 수정구
엔카 제휴사에서 선별한 차량입니다.
토마토렌트카는 중고차 신차 구분없이 1개월부터 60개월까지 신용심사 없이 누구나 이용 가능한 렌트 서비스를 제공합니다.
구매 가이드
허위매물 대처
압류 및 저당 처리
성능 상태 점검기록부
차량 금액 외 별도 수수료
차량 이전등록
차량 체크사항
알림등록
비슷한 조건의 동일한 모델이 신규매물로 등록되면 알려드릴까요?
알림등록
월100만원
월렌트료(1개월)
월렌트료도움말
보험료 계산
대출상품 조회
리스상품 조회
보증금
보증금자세히 보기
50 만원
차량가격
차량 가격 자세히 보기
4,010 만원
보험이력
비공개
신차가격표
판매자 문의하기
중고차시세
팔린매물
동급매물
엔카 중고차론
금융사 비교하고 제휴 추가할인
금리 4.9% 부터~
닫기
허위매물 단속 및 매매관련 분쟁 처리 등을 위해 050안심번호로문의하면 전화번호와 통화내용이 엔카에 자동 저장됩니다.050도움말
엔카는 등록 시스템만을 제공하며, 판매자가 직접 등록한 차량의 모든 책임은 판매자에게 있습니다. 신고하기
회사소개인재채용클린엔카지점안내엔카직영성능점검장안내매매지원이용약관고객센터디스플레이광고개인정보처리방침금융소비자보호원격지원서비스
네이버 블로그
인스타그램
유튜브
페이스북
패밀리사이트
O2O를 잇는 신뢰와 기술로 차량을 사고 파는 모습의 진화를 만듭니다
고객센터 : 1599-5455FAX : 02-754-8768대표

===== 후보 2 =====
tag   : div
id    :
class : g3KnCi7EkC
엔카
기본정보
옵션정보
렌트정보
보증현황
판매자 정보
딜러 셀프등록
로그인/회원가입
채팅
전체메뉴
열기
등록번호 40241113조회수 150찜 0
신고하기
프린트
공유하기
찜하기
#양호#HOT#COOL
엔카 실촬영
이전이미지
다음이미지
1 / 11
사진 모두보기
엔카 제휴사에서 선별한 차량입니다.
리스 · 렌트제휴 차량 검색
제휴사 소개
그랜저 (GN7)3.5 LPG 2WD프리미엄
연식
22/12식 (23년형)
연형정보
주행거리
51,000km
연료
LPG(일반인 구입)
차량번호
101하9880
자세히
옵션 정보더보기
주요옵션
옵션 설명 보기
선루프
있음
헤드램프
(LED)
있음
주차감지센서
있음
후방카메라
있음
자동에어컨
있음
스마트키
있음
내비게이션
있음
열선시트
있음
통풍시트
없음
가죽시트
있음
40개 옵션 모두보기
이 차만의 옵션더보기
파노라마 선루프 120만원
렌트 정보
차량 계약 시 비용
보증금 방식
50만원
운행기간 동안 비용
월렌트료 100만원 X 1개월
월렌트료 97만원 X 3개월
100만원
렌트 만기 후 비용
렌트 만기 후 비용
반납 (보증금 환급)
50만원
총비용
100만원
체크포인트
렌트방식 장기렌트
취등록세(7%) 면제
월렌트료 포함내역 자동차 세금보험료정비서비스
상환 스케줄표 없음
만기 후 처리 반납
렌트 정보 자세히 보기
보증 현황
제조사 보증제조사보증도움말
일반/차체
엔진/미션
엔카금융
1분만에 한도/금리 비교
다양한 금융사의 금리를 비교해보세요
방문없이 조회가 가능해요
신용점수에 영향이 없어요
금리 비교하기
판매자 정보
판매자정보사진
토마토렌트카|토마토렌트카반복
판매자 정보
판매중18판매완료0
경기 성남시 수정구
엔카 제휴사에서 선별한 차량입니다.
토마토렌트카는 중고차 신차 구분없이 1개월부터 60개월까지 신용심사 없이 누구나 이용 가능한 렌트 서비스를 제공합니다.
구매 가이드
허위매물 대처
압류 및 저당 처리
성능 상태 점검기록부
차량 금액 외 별도 수수료
차량 이전등록
차량 체크사항
알림등록
비슷한 조건의 동일한 모델이 신규매물로 등록되면 알려드릴까요?
알림등록
월100만원
월렌트료(1개월)
월렌트료도움말
보험료 계산
대출상품 조회
리스상품 조회
보증금
보증금자세히 보기
50 만원
차량가격
차량 가격 자세히 보기
4,010 만원
보험이력
비공개
신차가격표
판매자 문의하기
중고차시세
팔린매물
동급매물
엔카 중고차론
금융사 비교하고 제휴 추가할인
금리 4.9% 부터~
닫기
허위매물 단속 및 매매관련 분쟁 처리 등을 위해 050안심번호로문의하면 전화번호와 통화내용이 엔카에 자동 저장됩니다.050도움말
엔카는 등록 시스템만을 제공하며, 판매자가 직접 등록한 차량의 모든 책임은 판매자에게 있습니다. 신고하기
회사소개인재채용클린엔카지점안내엔카직영성능점검장안내매매지원이용약관고객센터디스플레이광고개인정보처리방침금융소비자보호원격지원서비스
네이버 블로그
인스타그램
유튜브
페이스북
패밀리사이트
O2O를 잇는 신뢰와 기술로 차량을 사고 파는 모습의 진화를 만듭니다
고객센터 : 1599-5455FAX : 02-754-8768대표

===== 후보 3 =====
tag   : div
id    :
class : XfOfmlE86r
엔카
기본정보
옵션정보
렌트정보
보증현황
판매자 정보
딜러 셀프등록
로그인/회원가입
채팅
전체메뉴
열기
등록번호 40241113조회수 150찜 0
신고하기
프린트
공유하기
찜하기
#양호#HOT#COOL
엔카 실촬영
이전이미지
다음이미지
1 / 11
사진 모두보기
엔카 제휴사에서 선별한 차량입니다.
리스 · 렌트제휴 차량 검색
제휴사 소개
그랜저 (GN7)3.5 LPG 2WD프리미엄
연식
22/12식 (23년형)
연형정보
주행거리
51,000km
연료
LPG(일반인 구입)
차량번호
101하9880
자세히
옵션 정보더보기
주요옵션
옵션 설명 보기
선루프
있음
헤드램프
(LED)
있음
주차감지센서
있음
후방카메라
있음
자동에어컨
있음
스마트키
있음
내비게이션
있음
열선시트
있음
통풍시트
없음
가죽시트
있음
40개 옵션 모두보기
이 차만의 옵션더보기
파노라마 선루프 120만원
렌트 정보
차량 계약 시 비용
보증금 방식
50만원
운행기간 동안 비용
월렌트료 100만원 X 1개월
월렌트료 97만원 X 3개월
100만원
렌트 만기 후 비용
렌트 만기 후 비용
반납 (보증금 환급)
50만원
총비용
100만원
체크포인트
렌트방식 장기렌트
취등록세(7%) 면제
월렌트료 포함내역 자동차 세금보험료정비서비스
상환 스케줄표 없음
만기 후 처리 반납
렌트 정보 자세히 보기
보증 현황
제조사 보증제조사보증도움말
일반/차체
엔진/미션
엔카금융
1분만에 한도/금리 비교
다양한 금융사의 금리를 비교해보세요
방문없이 조회가 가능해요
신용점수에 영향이 없어요
금리 비교하기
판매자 정보
판매자정보사진
토마토렌트카|토마토렌트카반복
판매자 정보
판매중18판매완료0
경기 성남시 수정구
엔카 제휴사에서 선별한 차량입니다.
토마토렌트카는 중고차 신차 구분없이 1개월부터 60개월까지 신용심사 없이 누구나 이용 가능한 렌트 서비스를 제공합니다.
구매 가이드
허위매물 대처
압류 및 저당 처리
성능 상태 점검기록부
차량 금액 외 별도 수수료
차량 이전등록
차량 체크사항
알림등록
비슷한 조건의 동일한 모델이 신규매물로 등록되면 알려드릴까요?
알림등록
월100만원
월렌트료(1개월)
월렌트료도움말
보험료 계산
대출상품 조회
리스상품 조회
보증금
보증금자세히 보기
50 만원
차량가격
차량 가격 자세히 보기
4,010 만원
보험이력
비공개
신차가격표
판매자 문의하기
중고차시세
팔린매물
동급매물
엔카 중고차론
금융사 비교하고 제휴 추가할인
금리 4.9% 부터~
닫기
허위매물 단속 및 매매관련 분쟁 처리 등을 위해 050안심번호로문의하면 전화번호와 통화내용이 엔카에 자동 저장됩니다.050도움말
엔카는 등록 시스템만을 제공하며, 판매자가 직접 등록한 차량의 모든 책임은 판매자에게 있습니다. 신고하기

===== 후보 4 =====
tag   : div
id    :
class : VXgDsJFc0r
엔카
기본정보
옵션정보
렌트정보
보증현황
판매자 정보
딜러 셀프등록
로그인/회원가입
채팅
전체메뉴
열기
등록번호 40241113조회수 150찜 0
신고하기
프린트
공유하기
찜하기
#양호#HOT#COOL
엔카 실촬영
이전이미지
다음이미지
1 / 11
사진 모두보기
엔카 제휴사에서 선별한 차량입니다.
리스 · 렌트제휴 차량 검색
제휴사 소개
그랜저 (GN7)3.5 LPG 2WD프리미엄
연식
22/12식 (23년형)
연형정보
주행거리
51,000km
연료
LPG(일반인 구입)
차량번호
101하9880
자세히
옵션 정보더보기
주요옵션
옵션 설명 보기
선루프
있음
헤드램프
(LED)
있음
주차감지센서
있음
후방카메라
있음
자동에어컨
있음
스마트키
있음
내비게이션
있음
열선시트
있음
통풍시트
없음
가죽시트
있음
40개 옵션 모두보기
이 차만의 옵션더보기
파노라마 선루프 120만원
렌트 정보
차량 계약 시 비용
보증금 방식
50만원
운행기간 동안 비용
월렌트료 100만원 X 1개월
월렌트료 97만원 X 3개월
100만원
렌트 만기 후 비용
렌트 만기 후 비용
반납 (보증금 환급)
50만원
총비용
100만원
체크포인트
렌트방식 장기렌트
취등록세(7%) 면제
월렌트료 포함내역 자동차 세금보험료정비서비스
상환 스케줄표 없음
만기 후 처리 반납
렌트 정보 자세히 보기
보증 현황
제조사 보증제조사보증도움말
일반/차체
엔진/미션
엔카금융
1분만에 한도/금리 비교
다양한 금융사의 금리를 비교해보세요
방문없이 조회가 가능해요
신용점수에 영향이 없어요
금리 비교하기
판매자 정보
판매자정보사진
토마토렌트카|토마토렌트카반복
판매자 정보
판매중18판매완료0
경기 성남시 수정구
엔카 제휴사에서 선별한 차량입니다.
토마토렌트카는 중고차 신차 구분없이 1개월부터 60개월까지 신용심사 없이 누구나 이용 가능한 렌트 서비스를 제공합니다.
구매 가이드
허위매물 대처
압류 및 저당 처리
성능 상태 점검기록부
차량 금액 외 별도 수수료
차량 이전등록
차량 체크사항
알림등록
비슷한 조건의 동일한 모델이 신규매물로 등록되면 알려드릴까요?
알림등록
월100만원
월렌트료(1개월)
월렌트료도움말
보험료 계산
대출상품 조회
리스상품 조회
보증금
보증금자세히 보기
50 만원
차량가격
차량 가격 자세히 보기
4,010 만원
보험이력
비공개
신차가격표
판매자 문의하기
중고차시세
팔린매물
동급매물
엔카 중고차론
금융사 비교하고 제휴 추가할인
금리 4.9% 부터~

In [20]:
# 가장 짧은 본문 후보 찾기

# 텍스트 길이 기준으로 정렬
candidates_sorted = sorted(candidates, key=lambda x: len(x["text"]))

print("가장 짧은 후보 미리보기:\n")
print(candidates_sorted[0]["text"][:2000])

가장 짧은 후보 미리보기:

엔카
기본정보
옵션정보
렌트정보
보증현황
판매자 정보
딜러 셀프등록
로그인/회원가입
채팅
전체메뉴
열기
등록번호 40241113조회수 150찜 0
신고하기
프린트
공유하기
찜하기
#양호#HOT#COOL
엔카 실촬영
이전이미지
다음이미지
1 / 11
사진 모두보기
엔카 제휴사에서 선별한 차량입니다.
리스 · 렌트제휴 차량 검색
제휴사 소개
그랜저 (GN7)3.5 LPG 2WD프리미엄
연식
22/12식 (23년형)
연형정보
주행거리
51,000km
연료
LPG(일반인 구입)
차량번호
101하9880
자세히
옵션 정보더보기
주요옵션
옵션 설명 보기
선루프
있음
헤드램프
(LED)
있음
주차감지센서
있음
후방카메라
있음
자동에어컨
있음
스마트키
있음
내비게이션
있음
열선시트
있음
통풍시트
없음
가죽시트
있음
40개 옵션 모두보기
이 차만의 옵션더보기
파노라마 선루프 120만원
렌트 정보
차량 계약 시 비용
보증금 방식
50만원
운행기간 동안 비용
월렌트료 100만원 X 1개월
월렌트료 97만원 X 3개월
100만원
렌트 만기 후 비용
렌트 만기 후 비용
반납 (보증금 환급)
50만원
총비용
100만원
체크포인트
렌트방식 장기렌트
취등록세(7%) 면제
월렌트료 포함내역 자동차 세금보험료정비서비스
상환 스케줄표 없음
만기 후 처리 반납
렌트 정보 자세히 보기
보증 현황
제조사 보증제조사보증도움말
일반/차체
엔진/미션
엔카금융
1분만에 한도/금리 비교
다양한 금융사의 금리를 비교해보세요
방문없이 조회가 가능해요
신용점수에 영향이 없어요
금리 비교하기
판매자 정보
판매자정보사진
토마토렌트카|토마토렌트카반복
판매자 정보
판매중18판매완료0
경기 성남시 수정구
엔카 제휴사에서 선별한 차량입니다.
토마토렌트카는 중고차 신차 구분없이 1개월부터 60개월까지 신용심사 없이 누구나 이용 가능한 렌트 서비스를 제공합니다.
구매 가이드
허위매물 대처
압류 및 저당 처리
성능 상태 점검기록부
차량 금액 외 별도 수수료
차량 이전등록
차량 체크사항
알림등록
비슷한 조건의 동일한 모델이 신규매물로 등록되면 알려드릴까요?
알림등록
월100만원
월렌트료(1개월)
월렌트료도움말
보험료 계산
대출상품 조회
리스상품 조회
보증금
보증금자세히 보기
50 만원
차량가격
차량 가격 자세히 보기
4,010 만원
보험이력
비공개
신차가격표
판매자 문의하기
중고차시세
팔린매물
동급매물
엔카 중고차론
금융사 비교하고 제휴 추가할인
금리 4.9% 부터~

In [21]:
# 현재 페이지에 차량명이 보이는지 직접 검색

from selenium.webdriver.common.by import By

# 현재 문맥에서 '그랜저'가 들어간 보이는 요소 찾기
elems = driver.find_elements(By.XPATH, "//*[contains(normalize-space(.), '그랜저')]")

visible_elems = []
for e in elems:
    try:
        if e.is_displayed():
            txt = e.text.strip()
            if txt:
                visible_elems.append(txt)
    except:
        pass

# 중복 제거
visible_unique = []
seen = set()
for t in visible_elems:
    if t not in seen:
        visible_unique.append(t)
        seen.add(t)

print("현재 문맥에서 보이는 '그랜저' 요소 수:", len(visible_unique))
for i, t in enumerate(visible_unique[:10], 1):
    print(f"\n[{i}]")
    print(t[:300])

현재 문맥에서 보이는 '그랜저' 요소 수: 7

[1]
엔카
기본정보
옵션정보
렌트정보
보증현황
판매자 정보
딜러 셀프등록
로그인/회원가입
채팅
전체메뉴
열기
등록번호 40241113조회수 150찜 0
신고하기
프린트
공유하기
찜하기
#양호#HOT#COOL
엔카 실촬영
이전이미지
다음이미지
1 / 11
사진 모두보기
엔카 제휴사에서 선별한 차량입니다.
리스 · 렌트제휴 차량 검색
제휴사 소개
그랜저 (GN7)3.5 LPG 2WD프리미엄
연식
22/12식 (23년형)
연형정보
주행거리
51,000km
연료
LPG(일반인 구입)
차량번호
101하9880
자세히
옵션 정보더보기
주요옵션
옵션

[2]
엔카
기본정보
옵션정보
렌트정보
보증현황
판매자 정보
딜러 셀프등록
로그인/회원가입
채팅
전체메뉴
열기
등록번호 40241113조회수 150찜 0
신고하기
프린트
공유하기
찜하기
#양호#HOT#COOL
엔카 실촬영
이전이미지
다음이미지
1 / 11
사진 모두보기
엔카 제휴사에서 선별한 차량입니다.
리스 · 렌트제휴 차량 검색
제휴사 소개
그랜저 (GN7)3.5 LPG 2WD프리미엄
연식
22/12식 (23년형)
연형정보
주행거리
51,000km
연료
LPG(일반인 구입)
차량번호
101하9880
자세히
옵션 정보더보기
주요옵션
옵션

[3]
엔카
기본정보
옵션정보
렌트정보
보증현황
판매자 정보
딜러 셀프등록
로그인/회원가입
채팅
전체메뉴
열기
등록번호 40241113조회수 150찜 0
신고하기
프린트
공유하기
찜하기
#양호#HOT#COOL
엔카 실촬영
이전이미지
다음이미지
1 / 11
사진 모두보기
엔카 제휴사에서 선별한 차량입니다.
리스 · 렌트제휴 차량 검색
제휴사 소개
그랜저 (GN7)3.5 LPG 2WD프리미엄
연식
22/12식 (23년형)
연형정보
주행거리
51,000km
연료
LPG(일반인 구입)
차량번호
101하9880
자세히
옵션 정보더보기
주요옵션
옵션

[4]
그랜저 (GN7)3.5 LPG 2WD프리미엄
연식
22/12식 (23년형)
연형정보
주행거리
51,000km
연료
LPG(일반인 구입)
차량번호
101하9880
자세히
옵션 정보더보기
주요옵션
옵션 설명 보기
선루프
있음
헤드램프
(LED)
있음
주차감지센서
있음
후방카메라
있음
자동에어컨
있음
스마트키
있음
내비게이션
있음
열선시트
있음
통풍시트
없음
가죽시트
있음
40개 옵션 모두보기
이 차만의 옵션더보기
파노라마 선루프 120만원
렌트 정보
차량 계약 시 비용
보증금 방식
50만원
운행기간 동안 비용
월렌트료 100만원 X 1

[5]
그랜저 (GN7)3.5 LPG 2WD프리미엄
연식
22/12식 (23년형)
연형정보
주행거리
51,000km
연료
LPG(일반인 구입)
차량번호
101하9880
자세히

[6]
그랜저 (GN7)3.5 LPG 2WD프리미엄

[7]
그랜저 (GN7)

In [22]:
# iframe 화인

iframes = driver.find_elements(By.TAG_NAME, "iframe")

print("iframe 개수:", len(iframes))

for i, f in enumerate(iframes[:10], 1):
    print(f"\n[{i}]")
    print("id   :", f.get_attribute("id"))
    print("name :", f.get_attribute("name"))
    print("src  :", f.get_attribute("src"))

iframe 개수: 6

[1]
id   :
name :
src  : https://automotive.encar.com/RealMedia/ads/adstream_sx.ads/encar.com/dc_detail@Bottom?city=002&company=detail_Hyundai&detail_ca_Big=checked&fuel_detail=003&mileage=section3&modelGroup=detail_Hyundai_Grandeur&pageid=dc&price=PM4000&salesmethod=rent&seller=rent&service=none&year=2022&adconnection=

[2]
id   :
name :
src  : https://automotive.encar.com/RealMedia/ads/adstream_sx.ads/encar.com/dc_detail@Left?

[3]
id   :
name :
src  : https://automotive.encar.com/RealMedia/ads/adstream_sx.ads/encar.com/dc_detail@Right?city=002&company=detail_Hyundai&detail_ca_Big=checked&fuel_detail=003&mileage=section3&modelGroup=detail_Hyundai_Grandeur&pageid=dc&price=PM4000&salesmethod=rent&seller=rent&service=none&year=2022&adconnection=

[4]
id   :
name :
src  : https://automotive.encar.com/RealMedia/ads/adstream_sx.ads/encar.com/dc_detail@x51?

[5]
id   :
name :
src  : https://automotive.encar.com/RealMedia/ads/adstream_sx.ads/encar.com/dc_detail@x52?

[6]
id   :
name :
src  : https://automotive.encar.com/RealMedia/ads/adstream_sx.ads/encar.com/dc_detail@x53?

In [23]:
# iframe 안에서 차량명 찾기

driver.switch_to.default_content()

found = False

iframes = driver.find_elements(By.TAG_NAME, "iframe")

for idx in range(len(iframes)):
    driver.switch_to.default_content()
    iframes = driver.find_elements(By.TAG_NAME, "iframe")
    
    try:
        driver.switch_to.frame(iframes[idx])
        elems = driver.find_elements(By.XPATH, "//*[contains(normalize-space(.), '그랜저')]")
        
        visible_texts = []
        for e in elems:
            try:
                if e.is_displayed():
                    txt = e.text.strip()
                    if txt:
                        visible_texts.append(txt)
            except:
                pass
        
        unique_texts = []
        seen = set()
        for t in visible_texts:
            if t not in seen:
                unique_texts.append(t)
                seen.add(t)
        
        if unique_texts:
            print(f"[성공] iframe {idx} 안에서 '그랜저' 발견")
            for i, t in enumerate(unique_texts[:10], 1):
                print(f"\n[{i}]")
                print(t[:300])
            found = True
            break
    
    except Exception as e:
        print(f"iframe {idx} 확인 중 에러:", e)

if not found:
    print("iframe 안에서도 '그랜저'를 찾지 못했어.")

iframe 안에서도 '그랜저'를 찾지 못했어.

In [24]:
# 차량명/가격/km 같은 핵심 요소만 좁게 찾기

keywords = ["그랜저", "만원", "km", "주행거리", "연료", "변속기", "배기량"]

elems = driver.find_elements(
    By.XPATH,
    "//*[self::h1 or self::h2 or self::h3 or self::div or self::span or self::li or self::dd or self::dt or self::strong]"
)

matches = []

for e in elems:
    try:
        if not e.is_displayed():
            continue
        
        txt = e.text.strip()
        if not txt:
            continue
        
        # 너무 긴 블록 제외
        if len(txt) > 300:
            continue
        
        # 키워드 포함 여부
        if any(k in txt for k in keywords):
            matches.append(txt)
    except:
        pass

# 중복 제거
unique_matches = []
seen = set()
for t in matches:
    if t not in seen:
        unique_matches.append(t)
        seen.add(t)

print("핵심 후보 수:", len(unique_matches))
for i, t in enumerate(unique_matches[:30], 1):
    print(f"\n[{i}]")
    print(t)

핵심 후보 수: 0

In [25]:
# 페이지 완전히 로드될 때까지 기다리기

from selenium.webdriver.support.ui import WebDriverWait

wait = WebDriverWait(driver, 20)

wait.until(lambda d: d.execute_script("return document.readyState") == "complete")
time.sleep(5)

print("문서 로드 완료")
print("현재 URL:", driver.current_url)
print("페이지 제목:", driver.title)

문서 로드 완료
현재 URL: https://fem.encar.com/cars/detail/40241113?pageid=dc_carsearch&listAdvType=pic&carid=40241113&view_type=normal&wtClick_korList=015&advClickPosition=kor_pic_p1_g1
페이지 제목: 그랜저 (GN7) 3.5 LPG 2WD 프리미엄 경기 중고차 : 내차팔기·내차사기

In [26]:
# page_source 안에 차량 정보가 있는지 확인

html = driver.page_source

keywords = ["그랜저", "40241113", "만원", "km", "주행거리", "기본정보"]

for kw in keywords:
    print(f"{kw} 포함 여부:", kw in html)

print("HTML 길이:", len(html))

그랜저 포함 여부: False
40241113 포함 여부: False
만원 포함 여부: False
km 포함 여부: False
주행거리 포함 여부: False
기본정보 포함 여부: False
HTML 길이: 525

In [27]:
# 현재 화면 스크린샷 저장

driver.save_screenshot("detail_page_check.png")
print("스크린샷 저장 완료: detail_page_check.png")

스크린샷 저장 완료: detail_page_check.png

In [28]:
# Shadow DOM 존재 여부 확인

shadow_hosts = driver.execute_script("""
const all = [...document.querySelectorAll('*')];
return all
  .filter(el => el.shadowRoot)
  .map(el => ({
    tag: el.tagName,
    id: el.id,
    className: el.className
  }))
  .slice(0, 30);
""")

print("shadow host 개수:", len(shadow_hosts))
for i, host in enumerate(shadow_hosts, 1):
    print(f"\n[{i}] {host}")

shadow host 개수: 0

In [29]:
# 특수포함 요소 확인

print("iframe :", len(driver.find_elements(By.TAG_NAME, "iframe")))
print("frame  :", len(driver.find_elements(By.TAG_NAME, "frame")))
print("object :", len(driver.find_elements(By.TAG_NAME, "object")))
print("embed  :", len(driver.find_elements(By.TAG_NAME, "embed")))
print("canvas :", len(driver.find_elements(By.TAG_NAME, "canvas")))
print("svg    :", len(driver.find_elements(By.TAG_NAME, "svg")))
print("img    :", len(driver.find_elements(By.TAG_NAME, "img")))

iframe : 0
frame  : 0
object : 0
embed  : 0
canvas : 0
svg    : 0
img    : 1

In [30]:
# 화면 중앙에 실제로 어떤 요소가 있는지 확인

viewport_info = driver.execute_script("""
const x = window.innerWidth * 0.6;
const y = window.innerHeight * 0.4;
return document.elementsFromPoint(x, y).map(el => ({
  tag: el.tagName,
  id: el.id,
  className: el.className,
  text: (el.innerText || '').slice(0, 100)
})).slice(0, 20);
""")

for i, item in enumerate(viewport_info, 1):
    print(f"[{i}] {item}")

[1] {'className': '', 'id': '', 'tag': 'IMG', 'text': ''}
[2] {'className': '', 'id': '', 'tag': 'BODY', 'text': ''}
[3] {'className': '', 'id': '', 'tag': 'HTML', 'text': ''}

In [31]:
# JS로 실제 보이는 텍스트 노드 추출

visible_texts = driver.execute_script("""
const results = [];
const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);

while (walker.nextNode()) {
    const node = walker.currentNode;
    const text = node.textContent.trim();
    if (!text) continue;

    const parent = node.parentElement;
    if (!parent) continue;

    const style = window.getComputedStyle(parent);
    const rect = parent.getBoundingClientRect();

    if (style.display === 'none' || style.visibility === 'hidden') continue;
    if (rect.width === 0 || rect.height === 0) continue;

    results.push(text);
}

return [...new Set(results)].slice(0, 300);
""")

print("보이는 텍스트 수:", len(visible_texts))
for i, t in enumerate(visible_texts[:50], 1):
    print(f"\n[{i}] {t}")

보이는 텍스트 수: 0

In [32]:
# 스크립트 안에 데이터가 숨어있는지 확인

script_hits = driver.execute_script("""
const texts = [...document.scripts].map(s => s.textContent || '');
const joined = texts.join('\\n');
return {
  has_grandeur: joined.includes('그랜저'),
  has_won: joined.includes('만원'),
  has_km: joined.includes('km'),
  length: joined.length
};
""")

print(script_hits)

{'has_grandeur': False, 'has_km': False, 'has_won': False, 'length': 0}